# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on:
  push:
    branches:
      - 1.21.4-fabric
    tags:
      - v*.*.*
  pull_request:
    branches:
      - 1.21.4-fabric
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
            21, # Current Java LTS
          ]
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: "microsoft"
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: copy artifacts to root
        run: "find './build/libs'
          -maxdepth 1
          -name '*.jar'
          ! -name '*-dev-shadow.jar'
          ! -name '*-sources.jar'
          -exec cp -t ./ {} +"
      - name: capture build artifacts
        if: ${{ matrix.java == '21' }} # Only upload artifacts built from latest java
        uses: actions/upload-artifact@v4
        with:
          name: Built jars
          path: "*.jar"
      - name: release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            LICENSE
            *.jar
      - name: upload build reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: Reports
          path: build/reports/
